services:

  grafana:
    image: grafana/grafana:7.4.2
    ports:
      - 3000:3000
    volumes:
      - ./configs/grafana/provisioning/:/etc/grafana/provisioning/

  influxdb:
    image: influxdb:2.1.1
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=username
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=organisation
      - DOCKER_INFLUXDB_INIT_BUCKET=device-status
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
      - DOCKER_INFLUXDB_INIT_RETENTION=1w

  kafka:
    image: spotify/kafka

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_TOKEN=token
      - INFLUXDB_BUCKET=device-status
      - INFLUXDB_ORG=organisation
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=device-status

  device-0:
    build:
      context: ./device
      dockerfile: Dockerfile
    environment:
      - NAME=device-0
      - PERIOD=2  # seconds
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=device-status

  device-1:
    build:
      context: ./device
      dockerfile: Dockerfile
    environment:
      - NAME=device-1
      - PERIOD=10  # seconds
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=device-status
