apiVersion: 1

datasources:
  - name: device-status
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: token
    jsonData:
      version: Flux
      organization: organisation
      defaultBucket: device-status
      tlsSkipVerify: true
